import { Destination, Listing, Review } from './types';

export const DESTINATIONS: Destination[] = [
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    description: 'The City of Light shines with history, culinary masterpieces, and world-renowned art masterpieces.',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewCount: 312500
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    description: 'A dazzling mixture of ultra-modern skyscrapers, ancient temples, tranquil gardens, and culinary icons.',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewCount: 245300
  },
  {
    id: 'rome',
    name: 'Rome',
    country: 'Italy',
    description: 'A colossal exhibit of outdoor museums, dynamic plazas, world-famous monuments, and exquisite pasta.',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewCount: 198200
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    description: 'A tropical paradise characterized by spectacular volcanic mountains, iconic rice terraces, and coral beaches.',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewCount: 173100
  },
  {
    id: 'new-york',
    name: 'New York City',
    country: 'United States',
    description: 'The city that never sleeps, known for Broadway spectacles, towering monoliths, and central parks of absolute green.',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewCount: 289400
  }
];

export const LISTINGS: Listing[] = [
  // PARIS
  {
    id: 'par-h1',
    cityId: 'paris',
    name: 'Hôtel Plaza Athénée',
    category: 'hotel',
    rating: 4.9,
    reviewCount: 1240,
    price: 950,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=600',
    location: 'Avenue Montaigne, 8th Arrondissement, Paris',
    description: 'On the prestigious Avenue Montaigne, this legendary luxury palace features beautiful Parisian balconies with bold red awnings, offering iconic, unobstructed views of the Eiffel Tower inside a classical French structure.',
    features: ['Eiffel Tower view', 'Michelin-starred dining', 'Dior Spa', 'Free High-Speed Wi-Fi', '24-Hour Butler Services', 'Valet Parking']
  },
  {
    id: 'par-h2',
    cityId: 'paris',
    name: 'Le Bristol Paris',
    category: 'hotel',
    rating: 4.8,
    reviewCount: 940,
    price: 1100,
    image: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&q=80&w=600',
    location: 'Rue du Faubourg Saint-Honoré, Paris',
    description: 'An icon of French art de vivre, Le Bristol represents the pinnacle of classical elegance, offering a gorgeous inner garden courtyard, a spectacular rooftop indoor pool, and exceptional 3-star Michelin cuisine.',
    features: ['Rooftop Swimming Pool', 'Michelin 3-Star Restaurant', 'Inner Courtyard Garden', 'Pet Friendly', 'Luxury Spa']
  },
  {
    id: 'par-h3',
    cityId: 'paris',
    name: 'Hotel Boutique Saint-Germain',
    category: 'hotel',
    rating: 4.5,
    reviewCount: 310,
    price: 240,
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80&w=600',
    location: 'Left Bank, Saint-Germain-des-Prés, Paris',
    description: 'A charming, authentic Parisian experience on the Left Bank. Features carefully themed antique decor, freshly baked local croissants delivered every morning, and high-quality vintage aesthetics.',
    features: ['Boutique Design', 'French Breakfast In-Bed', 'Historic Left Bank Location', 'Eco-friendly', 'Concierge Tour Desk']
  },
  {
    id: 'par-r1',
    cityId: 'paris',
    name: "L'Ambroisie",
    category: 'restaurant',
    rating: 4.9,
    reviewCount: 420,
    price: 280,
    image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&q=80&w=600',
    location: 'Place de Vosges, Marais, Paris',
    description: 'Located in the historic Place des Vosges, L’Ambroisie serves immaculate classical French haute cuisine in an elegant, candlelit renaissance salon. Truly a bucket list gastronomy experience.',
    features: ['3 Michelin Stars', 'Historic Marais Palace', 'Classic Tasting Menu', 'Romantic Candlelit Ambience', 'Exquisite Wine List']
  },
  {
    id: 'par-r2',
    cityId: 'paris',
    name: 'Le Comptoir du Relais',
    category: 'restaurant',
    rating: 4.6,
    reviewCount: 1450,
    price: 65,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=600',
    location: 'Carrefour de l’Odéon, Paris',
    description: 'Chef Yves Camdeborde revolutionized traditional dining with his accessible bistro gastronomy concept here. Incredible gourmet dishes served in a lively, intimate, and friendly corner bistro.',
    features: ['Bistronomy Pioneer', 'Outdoor Terrace Dining', 'Local Artisanal Cheeses', 'Cozy Parisian Vibe', 'Reservations Recommended']
  },
  {
    id: 'par-r3',
    cityId: 'paris',
    name: 'Café de Flore',
    category: 'restaurant',
    rating: 4.2,
    reviewCount: 3820,
    price: 30,
    image: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&q=80&w=600',
    location: 'Boulevard Saint-Germain, Paris',
    description: 'One of the oldest and most prestigious coffeehouses in Paris, famous for its historic high-society clientele including Jean-Paul Sartre, Picasso, and Hemingway. Excellent for people watching over an espresso.',
    features: ['Philosophical History', 'Iconic Hot Chocolate', 'Sidewalk Cafe Tables', 'All-Day Croque Monsieur', 'Iconic Souvenir Plates']
  },
  {
    id: 'par-a1',
    cityId: 'paris',
    name: 'Eiffel Tower Premium Summit Tour',
    category: 'attraction',
    rating: 4.8,
    reviewCount: 18900,
    price: 45,
    image: 'https://images.unsplash.com/photo-1543349689-9a4d426bee8e?auto=format&fit=crop&q=80&w=600',
    location: 'Champ de Mars, 5 Avenue Anatole France, Paris',
    description: 'Bypass the immense lines with a dedicated local guide and take the glass elevator directly up to the summit of the Eiffel Tower, culminating in a jaw-dropping panoramic view over the entire Parisian skyline.',
    features: ['Skip-The-Line Access', 'Professional Local Guide', 'Highest Observation Terrace', 'Includes Summit Champagne Bar', 'Mobile Voucher Accepted']
  },
  {
    id: 'par-a2',
    cityId: 'paris',
    name: 'Louvre Museum Masterpieces Tour',
    category: 'attraction',
    rating: 4.7,
    reviewCount: 14200,
    price: 65,
    image: 'https://images.unsplash.com/photo-1601887389937-0b02c26b6c3c?auto=format&fit=crop&q=80&w=600',
    location: 'Rue de Rivoli, Paris',
    description: 'Optimize your exploration of the largest museum in the world. This expertly guided tour routes you seamlessly to the Mona Lisa, Venus de Milo, Winged Victory, and other incredible historic relics.',
    features: ['Guided Walking Tour', 'Audio Commentary Headsets', 'Guaranteed Fast Entrance', 'Small Groups (Max 15)', 'Includes Daily Museum Ticket']
  },
  {
    id: 'par-v1',
    cityId: 'paris',
    name: 'Charming Marais Loft with Balcony',
    category: 'rental',
    rating: 4.7,
    reviewCount: 189,
    price: 180,
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=600',
    location: 'Rue des Rosiers, Marais, Paris',
    description: 'A beautifully restored 17th-century wood-beamed loft inside the trendy Marais district, complete with a private flower-filled wrought-iron balcony to enjoy fresh morning pastries.',
    features: ['Charming Wrought-Iron Balcony', 'Restored 17th-Century Beams', 'Fully Equipped Kitchenette', 'Washing Machine', 'Authentic Parisian Feel']
  },

  // TOKYO
  {
    id: 'tok-h1',
    cityId: 'tokyo',
    name: 'Aman Tokyo',
    category: 'hotel',
    rating: 4.9,
    reviewCount: 520,
    price: 1400,
    image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&q=80&w=600',
    location: 'The Otemachi Tower, Chiyoda City, Tokyo',
    description: 'Suspended high above Otemachi, Aman Tokyo balances absolute architectural minimalism with traditional Japanese design principles, using sliding shoji screens, washi paper, and deep Hinoki stone bath tubes.',
    features: ['Panoramic Skyline Spas', 'Deep Hinoki Soaking Tub', 'Floor-to-ceiling Glass Walls', 'Zen Garden Atrium', 'Lobby Sake Lounge', '25M Heated Pool']
  },
  {
    id: 'tok-h2',
    cityId: 'tokyo',
    name: 'Park Hyatt Tokyo',
    category: 'hotel',
    rating: 4.7,
    reviewCount: 1100,
    price: 750,
    image: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&q=80&w=600',
    location: 'Nishi-Shinjuku, Shinjuku City, Tokyo',
    description: 'A legendary beacon of luxury perched atop the Shinjuku Park Tower. Made famous in cinematic history (Lost in Translation), featuring the iconic 52nd-floor New York Bar with incredible Mount Fuji sights.',
    features: ['Lost in Translation Icon', '52nd-floor New York Bar', 'Spectacular Mount Fuji Views', 'High-tech Luxury Rooms', 'World-class Gym & Spa']
  },
  {
    id: 'tok-h3',
    cityId: 'tokyo',
    name: 'Shinjuku Granbell Hotel',
    category: 'hotel',
    rating: 4.3,
    reviewCount: 890,
    price: 150,
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&q=80&w=600',
    location: 'Kabukicho, Shinjuku, Tokyo',
    description: 'A unique artistic hotel situated deep in the heart of the energetic Kabukicho district, with custom-designed designer suites and an incredible open-air rooftop bar and terrace overlooking Tokyo nights.',
    features: ['Rooftop Sky Bar', 'Modern Artistic Design', 'Heart of Kabukicho', 'Steps from Golden Gai', 'In-room Espresso Machine']
  },
  {
    id: 'tok-r1',
    cityId: 'tokyo',
    name: 'Sukiyabashi Jiro',
    category: 'restaurant',
    rating: 4.8,
    reviewCount: 310,
    price: 350,
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&q=80&w=600',
    location: 'Ginza, Chuo City, Tokyo',
    description: 'The legendary sushi sanctuary curated by Master Chef Jiro Ono. Offering a phenomenal 20-piece omakase menu that represents the absolute historical peak of Edo-style sushi craftsmanship.',
    features: ['Edo-Style Omakase Only', 'Historic Ginza Basement', 'Requires Advanced Waitlist', 'Prepared by Master Jiro', 'Fresh Daily Tsukiji Market Catch']
  },
  {
    id: 'tok-r2',
    cityId: 'tokyo',
    name: 'Ichiran Ichigo Shinjuku',
    category: 'restaurant',
    rating: 4.5,
    reviewCount: 4200,
    price: 15,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&q=80&w=600',
    location: 'Nishi-Shinjuku, Tokyo',
    description: 'The iconic tonkotsu ramen parlor known for its custom isolation booths. Patrons customize everything via ordering slips—including soup density, garlic texture, noodle texture, and chili levels.',
    features: ['Individual Isolation Booths', 'Customizable Tonkotsu Broth', 'Famous Hiden Chili Red Sauce', '24-Hour Operations', 'Fast Order Vending Machine']
  },
  {
    id: 'tok-a1',
    cityId: 'tokyo',
    name: 'teamLab Planets Digital Art Exhibition',
    category: 'attraction',
    rating: 4.9,
    reviewCount: 11200,
    price: 32,
    image: 'https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?auto=format&fit=crop&q=80&w=600',
    location: 'Toyosu, Koto City, Tokyo',
    description: 'Explore a breathtaking digital museum where you wander barefoot through vast water spaces and immerse your entire body inside colossal interactive projecting artwork projection rooms.',
    features: ['Barefoot Immersive Spaces', 'Incredible Photography Spots', 'Interactive Flower Exhibits', 'E-Ticket Instant Admission', 'Wheelchair Accessible Areas']
  },
  {
    id: 'tok-a2',
    cityId: 'tokyo',
    name: 'Asakusa & Senso-ji Historical Tour',
    category: 'attraction',
    rating: 4.7,
    reviewCount: 7800,
    price: 20,
    image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&q=80&w=600',
    location: 'Asakusa, Taito City, Tokyo',
    description: 'Journey back to old Edo. Walk through the majestic Thunder Gate, explore the bustling stalls of Nakamise Shopping Street, and admire the majestic classical structure of the historic Senso-ji Temple.',
    features: ['Expert Shinto-Buddhist Guide', 'Traditional Street Food Tastings', 'Fortune Paper Ritual', 'Small-Group Experiences', 'Duration: 2.5 Hours']
  },
  {
    id: 'tok-v1',
    cityId: 'tokyo',
    name: 'Traditional Machiya Townhouse in Asakusa',
    category: 'rental',
    rating: 4.8,
    reviewCount: 75,
    price: 220,
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&q=80&w=600',
    location: 'Asakusa, Tokyo',
    description: 'Experience living in a fully renovated historical Japanese townhouse complete with tatami mat floors, futon bedding, sliding shoji paper panels, and a charming stone garden pathway.',
    features: ['Authentic Tatami Floors', 'Traditional Stone Zen Garden', 'Deep Cedar Hinoki Soaking Bath', 'Modern Portable Wi-Fi', 'Quiet Residential Area']
  },

  // ROME
  {
    id: 'rom-h1',
    cityId: 'rome',
    name: 'Hotel de Russie',
    category: 'hotel',
    rating: 4.8,
    reviewCount: 680,
    price: 800,
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&q=80&w=600',
    location: 'Via del Babuino, Rome',
    description: 'Located between the Spanish Steps and Piazza del Popolo, this premium palace hotel is celebrated for its historic secret Mediterranean terraced gardens, offering a tranquil sanctuary in old Rome.',
    features: ['Secret Terraced Gardens', 'Cocteau Sky Bar', 'Rocco Forte Luxury Spa', 'Steps from Piazza del Popolo', 'Elegant Italian Finishes']
  },
  {
    id: 'rom-h2',
    cityId: 'rome',
    name: 'Singer Palace Hotel',
    category: 'hotel',
    rating: 4.9,
    reviewCount: 420,
    price: 450,
    image: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&q=80&w=600',
    location: 'Via del Corso, Rome',
    description: 'An elegant boutique hotel housed in a historic 20th-century art-deco building. Boasts a gorgeous rooftop restaurant overlooking the Roman city layout, Trevi, and majestic marble streets.',
    features: ['Art Deco Marble Staircase', 'Panoramic Rooftop Dining', 'Boutique Personal Service', 'Central Via del Corso Location', 'Complimentary Champagne Welcome']
  },
  {
    id: 'rom-r1',
    cityId: 'rome',
    name: 'La Pergola',
    category: 'restaurant',
    rating: 4.9,
    reviewCount: 820,
    price: 250,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&q=80&w=600',
    location: 'Rome Cavalieri, Rome',
    description: "The only restaurant in Rome decorated with three Michelin Stars. Chef Heinz Beck serves brilliant modern reinventions of classical Italian dishes. Outstanding panoramic vistas of the Vatican.",
    features: ['3 Michelin Stars', 'Panoramic Vatican Terraces', 'Epic Ten-Course Menu', 'World-Class Caviar List', 'Extensive Antique Wine Cellar']
  },
  {
    id: 'rom-r2',
    cityId: 'rome',
    name: 'Da Enzo al 29',
    category: 'restaurant',
    rating: 4.7,
    reviewCount: 3400,
    price: 35,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=600',
    location: 'Trastevere, Rome',
    description: 'An tiny, rustic traditional trattoria tucked inside old Trastevere. Unbelievably rich classical Cacio e Pepe, Carbonara, and Amatrice Roman pasta sauces, prepared using authentic local ingredients.',
    features: ['Rustic Trastevere Vibe', 'Exceptional Pasta Carbonara', 'Authentic Roman Artichokes', 'Outdoor Street Tables', 'Long But Rewarding Lines']
  },
  {
    id: 'rom-a1',
    cityId: 'rome',
    name: 'Colosseum Underground & Arena Floor VIP Tour',
    category: 'attraction',
    rating: 4.9,
    reviewCount: 15400,
    price: 65,
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&q=80&w=600',
    location: 'Piazza del Colosseo, Rome',
    description: 'Step directly onto the newly reconstructed Arena Floor where gladiators clashed. Then descend into the rarely accessed underground tunnels and chambers where wild animals were once caged.',
    features: ['VIP Underground Credentials', 'Arena Floor Access Included', 'Expert Archaeologist Guide', 'Includes Roman Forum Ticket', 'Skip All Main Entrances']
  },
  {
    id: 'rom-a2',
    cityId: 'rome',
    name: 'Vatican Museums & Sistine Chapel Express Tour',
    category: 'attraction',
    rating: 4.8,
    reviewCount: 16200,
    price: 55,
    image: 'https://images.unsplash.com/photo-1527030280862-64139fbe04ca?auto=format&fit=crop&q=80&w=600',
    location: 'Vatican City, Rome',
    description: 'Bypass the four-hour ticketing lines and gain early access to Michelangelo’s extraordinary frescoes on the Sistine Chapel ceiling, followed by a fast exploration of Raphael’s magnificent chambers.',
    features: ['Early Morning Access VIP', 'Direct Basilica Access Door', 'Licensed Vatican Guide', 'Whisper Listening Headsets', 'Vatican Gallery Guide Included']
  },
  {
    id: 'rom-v1',
    cityId: 'rome',
    name: 'Trastevere Classic Apartment with Roof Terrace',
    category: 'rental',
    rating: 4.7,
    reviewCount: 142,
    price: 160,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=600',
    location: 'Vicolo del Cinque, Trastevere, Rome',
    description: 'A charming, warm Roman apartment featuring high wood-beamed ceilings, terracotta floors, and a gorgeous private rooftop terrace framed in climbing ivy, overlooking brick bell towers.',
    features: ['Ivy-Covered Rooftop Terrace', 'Terracotta Renaissance Floors', 'Air Conditioning', 'Espresso Maker', 'Heart of Trastevere']
  },

  // BALI
  {
    id: 'bal-h1',
    cityId: 'bali',
    name: 'Four Seasons Resort Sayan',
    category: 'hotel',
    rating: 4.9,
    reviewCount: 810,
    price: 900,
    image: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=600',
    location: 'Sayan, Ubud, Bali',
    description: 'A majestic resort suspended above the Ayung River valley. Enter across an architectural suspension bridge onto an immense rooftop lotus pond, leading down to jungle-wrapped timber villas.',
    features: ['Ocean-like Healing River Spas', 'Suspended Lotus Pool Plaza', 'Private Jungle Plunge Pools', 'Morning Rice Terrace Treks', 'Antigravity Yoga Pavilion']
  },
  {
    id: 'bal-h2',
    cityId: 'bali',
    name: 'The Kayon Jungle Resort',
    category: 'hotel',
    rating: 4.8,
    reviewCount: 650,
    price: 380,
    image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&q=80&w=600',
    location: 'Tegallalang, Ubud, Bali',
    description: 'A sanctuary of eternal wellness, boasting a magnificent three-tiered infinity swimming pool that beautifully replicates the curved geometry of ancient Balinese rice terrace hillsides.',
    features: ['Three-Tiered Infinity Pool', 'Breathtaking Valley Views', 'Daily Petulu Village Shuttles', 'Heavenly Serapy Wellness Spas', 'Traditional Balinese Architectures']
  },
  {
    id: 'bal-r1',
    cityId: 'bali',
    name: 'Locavore',
    category: 'restaurant',
    rating: 4.9,
    reviewCount: 910,
    price: 120,
    image: 'https://images.unsplash.com/photo-1428515613728-6b4607e44363?auto=format&fit=crop&q=80&w=600',
    location: 'Jalan Dewisita, Ubud, Bali',
    description: 'The premier culinary laboratory in Ubud, dedicated entirely to hyper-local ingredients sourced from surrounding farming villages and local waters. Prepare for a breathtaking modern tasting menu.',
    features: ['Hyper-Local Tasting Menus', 'No-Waste Kitchen Philosophy', 'Outstanding Cocktail Pairing', 'Open Culinary Labs', 'Requires Months-Prior Booking']
  },
  {
    id: 'bal-r2',
    cityId: 'bali',
    name: 'Naughty Nuri’s Warung Seminyak',
    category: 'restaurant',
    rating: 4.6,
    reviewCount: 2800,
    price: 25,
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&q=80&w=600',
    location: 'Jalan Raya Basangkasa, Seminyak, Bali',
    description: 'Famous for its insanely delicious street-style caramelized baby back ribs slathered in sticky local spices, and its fun, lively table-shipped dry martinis with impromptu ritual dancing.',
    features: ['World-Famous Caramelized Ribs', 'Shaken Table-side Martinis', 'Lively Fun Backyard Diner', 'Cheap Ice-Cold Local Bintang', 'Live Charcoal Smokers']
  },
  {
    id: 'bal-a1',
    cityId: 'bali',
    name: 'Uluwatu Temple Sunset & Kecak Fire Dance Show',
    category: 'attraction',
    rating: 4.8,
    reviewCount: 8900,
    price: 18,
    image: 'https://images.unsplash.com/photo-1517949900011-0d37e5f2c418?auto=format&fit=crop&q=80&w=600',
    location: 'Pecatu, South Kuta, Bali',
    description: 'A spiritual clifftop temple rising 70 meters above crashing surf waves. Followed by a phenomenal seaside sunset performance of the magnificent, rhythmic Kecak chants and fire rituals.',
    features: ['Clifftop Sunset Gateways', 'Rhythmic Kecak Fire Performance', 'Ocean View Cliff Walks', 'Includes Monkey Guardian Forest', 'Round-trip Air Conditioned Transport']
  },
  {
    id: 'bal-a2',
    cityId: 'bali',
    name: 'Sacred Monkey Forest Ubud Experience',
    category: 'attraction',
    rating: 4.6,
    reviewCount: 11200,
    price: 10,
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=600',
    location: 'Jalan Monkey Forest, Ubud, Bali',
    description: 'Journey inside an ancient moss-covered jungle sanctuary. Home to over 1000 wild long-tailed macaques playing in historical temple ruins, old banyan trees, and river ravines.',
    features: ['Over 1000 Wild Macaques', 'Mossy Hindu Temple Ruins', 'Gigantic Giant Banyan Woods', 'Official Forest Guides Included', 'Monkey Food & Snack Stalls']
  },
  {
    id: 'bal-v1',
    cityId: 'bali',
    name: 'Eco-Bamboo Palace in Ubud Forest',
    category: 'rental',
    rating: 4.9,
    reviewCount: 115,
    price: 140,
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=600',
    location: 'Sibang Gede, Ubud, Bali',
    description: 'A stunning, architectural work of art constructed entirely of sustainable local black bamboo. Perched directly above a rushing river, fully open-air to embrace jungle breezes.',
    features: ['All-Bamboo Eco Structure', 'Hanging Private Net Beds', 'Organic Plunge Pools', 'Fully Serviced Villa Cook', 'Overlooking Sacred River Canals']
  },

  // NEW YORK
  {
    id: 'ny-h1',
    cityId: 'new-york',
    name: 'The Plaza Hotel',
    category: 'hotel',
    rating: 4.7,
    reviewCount: 2450,
    price: 850,
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&q=80&w=600',
    location: 'Fifth Avenue at Central Park South, New York',
    description: 'An iconic, world-renowned Beaux-Arts landmark hotel situated proudly on Fifth Avenue and Central Park South. Offers the legendary Palm Court afternoon tea experience in gilded elegance.',
    features: ['Central Park South Entrance', 'Legendary Palm Court Teas', 'Gilded Beaux-Arts Ballrooms', '24-Karat Gold Plated Fixtures', 'Personal White-Glove Butler']
  },
  {
    id: 'ny-h2',
    cityId: 'new-york',
    name: 'The Standard High Line',
    category: 'hotel',
    rating: 4.6,
    reviewCount: 1680,
    price: 390,
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&q=80&w=600',
    location: '848 Washington St, Meatpacking District, New York',
    description: 'Hovering directly above the historic elevated High Line railway park in the trendy Meatpacking District, this minimalist glass tower offers wall-to-wall windows looking out onto the Hudson River.',
    features: ['Straddles High Line Park', 'Wall-of-Glass Skyline Views', 'Le Bain Rooftop Club', 'Standard Grill Dining', 'Free Cruiser Bicycles']
  },
  {
    id: 'ny-r1',
    cityId: 'new-york',
    name: 'Eleven Madison Park',
    category: 'restaurant',
    rating: 4.8,
    reviewCount: 1100,
    price: 400,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600',
    location: '11 Madison Ave, New York',
    description: 'An architectural and gastronomic masterpiece. Chef Daniel Humm serves a revolutionary, plant-based fine dining multicourse degustation menu overlooking gorgeous Madison Square Park.',
    features: ['3 Michelin Stars', 'Elegant Art Deco Tall Walls', '100% Plant-Based Fine Tasting', 'Exceptional Wine Pairing Labs', 'Reservations Release monthly']
  },
  {
    id: 'ny-r2',
    cityId: 'new-york',
    name: 'Katz’s Delicatessen',
    category: 'restaurant',
    rating: 4.7,
    reviewCount: 14500,
    price: 30,
    image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=600',
    location: '205 E Houston St, Lower East Side, New York',
    description: 'Serving legendary Jewish-style cured pastrami sandwiches in a nostalgic, cafeteria-style dining room since 1888. The quintessential food landmark of New York’s historic Lower East Side.',
    features: ['Nostalgic 1888 Assembly Hall', 'Legendary Hand-sliced Pastrami', 'Classic Kosher Pickles', 'As Seen in Harry Met Sally', 'Pass-by Ticket Vibe']
  },
  {
    id: 'ny-a1',
    cityId: 'new-york',
    name: 'Empire State Building Observatory Entrance',
    category: 'attraction',
    rating: 4.7,
    reviewCount: 22400,
    price: 44,
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&q=80&w=600',
    location: '350 Fifth Ave, Midtown Manhattan, New York',
    description: 'Stand high above midtown Manhattan from the celebrated 86th-floor open-air observatory. Capture beautiful, 360-degree sights across the skyline, riverways, and bridges.',
    features: ['86th-Floor Open-Air Deck', 'Iconic Art Deco Lobby Entry', 'Skip-Ticketing-Line Express Options', 'Includes Museum Gallery Access', 'Free Interactive Audio Guide App']
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r-01',
    listingId: 'par-h1',
    title: 'An absolute fairytale experience!',
    rating: 5,
    text: 'From the moment the red coats greeted us on Avenue Montaigne, we felt like royalty. The view of the Eiffel Tower from our floral balcony was worth every single euro. Getting warm croissants delivered each morning by a private butler service was unforgettable! Truly an iconic French masterpiece of hotellerie.',
    authorName: 'Sarah Jenkins',
    authorLocation: 'Boston, MA',
    date: '2026-05-15',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150'
  },
  {
    id: 'r-02',
    listingId: 'par-h1',
    title: 'Immense luxury but expensive',
    rating: 4,
    text: 'A gorgeous hotel with beautiful, museum-like rooms and outstanding service. The flowers in the lobby are spectacular. However, prices are incredibly high—even simple laundry or afternoon tea items carry extreme premiums. Best saved for highly special occasions.',
    authorName: 'David Chen',
    authorLocation: 'Vancouver, BC',
    date: '2026-04-10',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150'
  },
  {
    id: 'r-03',
    listingId: 'par-r1',
    title: 'Culinary perfection, best meal ever!',
    rating: 5,
    text: 'L’Ambroisie is proof that classical French cuisine remains supreme. Every bite of the truffle and sea bass puff pastry was otherworldly. Extremely quiet, private ambiance inside a historic Marais townhouse. Staff are professional and friendly without any pretense.',
    authorName: 'Jean-Pierre L.',
    authorLocation: 'Lyon, France',
    date: '2026-06-02',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150'
  },
  {
    id: 'r-04',
    listingId: 'tok-h1',
    title: 'The height of tranquil luxury',
    rating: 5,
    text: 'Perched thousands of feet above the concrete traffic of Otemachi, Aman Tokyo feels like a quiet temple floating in clouds. The Hinoki timber scents in the bathroom, the breathtaking minimalist stone swimming pools, and the massive stone garden in the lobby created ultimate peace. Truly beautiful!',
    authorName: 'Emily Watson',
    authorLocation: 'London, UK',
    date: '2026-06-11',
    userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=150'
  },
  {
    id: 'r-05',
    listingId: 'tok-r1',
    title: 'A holy temple of sushi',
    rating: 5,
    text: 'Getting a seat here felt like winning the lottery. Master Jiro Ono serves sushi at an intense, breathtaking pace. Each piece is perfectly molded, seasoned, and optimized for immediate tasting. It was an overwhelming display of master-level culinary focus.',
    authorName: 'Kenji Takahashi',
    authorLocation: 'Kyoto, Japan',
    date: '2026-05-20',
    userAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=150'
  },
  {
    id: 'r-06',
    listingId: 'ny-r2',
    title: 'The ultimate Pastrami sandwich!',
    rating: 5,
    text: 'A packed, hectic, noisy room but the food completely justifies the chaos. The pastrami is so exceptionally soft, warm, and spicy it literally melts in your mouth. Bring cash, watch your ticket, and secure a generous tip for the cutter. Legendary for a reason.',
    authorName: 'Michael Miller',
    authorLocation: 'Brooklyn, NY',
    date: '2026-05-30',
    userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150'
  }
];
